spring:
    application:
        name: tools
nacos:
    config:
        auto-refresh: true
        server-addr: 118.25.64.160:8848
        data-id: tools-prod.yaml
        group: DEFAULT_GROUP
        type: yaml

