server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:toolkey.p12
    key-alias: ${simpletools.ssl.key-alias}
    key-store-password: ${simpletools.ssl.key-store-password}
    key-store-type: ${simpletools.ssl.key-store-type}
spring:
    application:
      name: simple_tools
    profiles:
      active: prod
    datasource:
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${simpletools.mysql.host}:${simpletools.mysql.port}/${simpletools.mysql.db}
        username: ${simpletools.mysql.username}
        password: ${simpletools.mysql.password}
    redis:
        database: 0
        host: ${simpletools.redis.host}
        password: ${simpletools.redis.password}
        timeout: 6000
        jedis:
            pool:
                max-active: 8
                max-wait: 1000
                max-idle: 100
                min-idle: -1

jwt:
  secret: ${simpletools.jwt.secret}

wx:
  mp:
    appId: ${simpletools.wx.appId}
    secret: ${simpletools.wx.secret}
    token: ${simpletools.wx.token}
    aesKey: ${simpletools.wx.aesKey}
    callback: ${simpletools.wx.callback}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
